#!/usr/bin/env python3
"""
FER Plot Generator
==================
Reads FER.json files from one or more directories and generates a TikZ/pgfplots
LaTeX figure with a logarithmic y-axis (FER) over physical error probability epsilon.

Usage:
    python latex_plot.py dir1 dir2 dir3 ...
    python latex_plot.py dir1 dir2 --output my_plot.tex
    python latex_plot.py dir1 dir2 --labels "Code A" "Code B"
"""

import json
import sys
import argparse
import math
from pathlib import Path


# ── KIT colour cycle ──────────────────────────────────────────────────────────
COLORS = [
    ("kit-green",  "RGB", "0, 150, 130"),
    ("kit-blue",   "RGB", "70, 100, 170"),
    ("kit-red",    "RGB", "162, 34, 35"),
    ("kit-orange", "RGB", "223, 155, 27"),
    ("kit-yellow", "RGB", "252, 229, 0"),
]

MARKS = ["*", "triangle*", "square*", "diamond*", "pentagon*",
         "o", "triangle", "square", "diamond"]


def load_fer(directory: str) -> dict[float, float]:
    """Load FER.json from *directory* and return a sorted dict {epsilon: FER}."""
    path = Path(directory) / "FER.json"
    if not path.exists():
        raise FileNotFoundError(f"No FER.json found in '{directory}'")
    with open(path) as f:
        raw = json.load(f)
    return dict(sorted((float(k), float(v)) for k, v in raw.items()))


def make_label(directory: str) -> str:
    """Derive a legend label from the directory name."""
    return Path(directory).resolve().name.replace("_", " ")


def coordinates_block(data: dict[float, float]) -> str:
    """Format pgfplots coordinates string."""
    lines = ["        coordinates {"]
    for eps, fer in data.items():
        lines.append(f"            ({eps:.6g}, {fer:.6g})")
    lines.append("        };")
    return "\n".join(lines)


def generate_tex(dirs: list[str],
                 labels: list[str],
                 output: str,
                 xlabel: str = r"$\varepsilon$",
                 ylabel: str = r"\ac{FER}") -> None:

    # ── Collect data ──────────────────────────────────────────────────────────
    datasets = []
    for d, lbl in zip(dirs, labels):
        data = load_fer(d)
        datasets.append((lbl, data))

    # ── Determine axis bounds ─────────────────────────────────────────────────
    all_eps = [eps for _, d in datasets for eps in d]
    all_fer = [fer for _, d in datasets for fer in d if fer > 0]

    xmin = min(all_eps)
    xmax = max(all_eps)

    # round to a nice power-of-ten below the smallest FER
    ymin_exp = math.floor(math.log10(min(all_fer))) - 1
    ymin = 10 ** ymin_exp   # e.g. 1e-4

    # ── Color definitions ─────────────────────────────────────────────────────
    color_defs = []
    for name, model, rgb in COLORS:
        color_defs.append(f"\\definecolor{{{name}}}{{{model}}}{{{rgb}}}")
    color_block = "\n".join(color_defs)

    # ── Plot commands ─────────────────────────────────────────────────────────
    plot_commands = []
    for i, (lbl, data) in enumerate(datasets):
        color_name = COLORS[i % len(COLORS)][0]
        mark       = MARKS[i % len(MARKS)]
        coords     = coordinates_block(data)
        plot_commands.append(
            f"    \\addplot[\n"
            f"        color={color_name},\n"
            f"        mark={mark},\n"
            f"        mark size=1.5pt,\n"
            f"        mark options={{solid}},\n"
            f"    ]\n"
            f"{coords}\n"
            f"    \\addlegendentry{{{lbl}}}"
        )
    plot_block = "\n\n".join(plot_commands)

    # ── Assemble .tex ─────────────────────────────────────────────────────────
    tex = rf"""% Auto-generated by latex_plot.py
% Requires: pgfplots, xcolor  (add \usepackage{{pgfplots,xcolor}} to preamble)
% The ylabel uses \ac{{FER}} — requires acronym/glossaries package, or replace manually.

{color_block}

\begin{{tikzpicture}}
  \begin{{axis}}[
    width  = 0.75\textwidth,
    height = 0.75\textwidth,
    %% ── Axes ────────────────────────────────────────────────────────────────
    xmin = {xmin:.6g},   xmax = {xmax:.6g},
    ymin = {ymin:.6g},   ymax = 1,
    %% ── Labels ──────────────────────────────────────────────────────────────
    xlabel = {{{xlabel}}},
    ylabel = {{{ylabel}}},
    label style        = {{font=\large}},
    tick label style   = {{font=\normal}},
    xticklabel style   = {{/pgf/number format/fixed}},
    %% ── Scale ───────────────────────────────────────────────────────────────
    ymode = log,
    %% ── Grid ────────────────────────────────────────────────────────────────
    grid             = both,
    minor grid style = {{gray!25}},
    major grid style = {{gray!50}},
    %% ── Legend ──────────────────────────────────────────────────────────────
    legend pos = south east,
    legend style = {{
        font=\small,
        /tikz/every node/.style={{anchor=west}}
    }},
    %% ── Plots ───────────────────────────────────────────────────────────────
    every axis plot/.append style = {{line width = 1.25pt}},
  ]

    \node[
        draw,
        fill=white,
        anchor=north west,
        font=\normal,
        inner sep=4pt,
    ] at (axis description cs:0, 1) {{GB-A3}};

{plot_block}

  \end{{axis}}
\end{{tikzpicture}}
"""

    with open(output, "w") as f:
        f.write(tex)
    print(f"[✓] Written to: {output}")
    print(f"    Datasets  : {len(datasets)}")
    for lbl, data in datasets:
        print(f"      • {lbl}  ({len(data)} points, "
              f"ε ∈ [{min(data):.3g}, {max(data):.3g}])")


# ── CLI ───────────────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate a pgfplots FER figure from FER.json files.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument(
        "directories",
        nargs="+",
        metavar="DIR",
        help="Directories containing a FER.json file (pass as many as you like).",
    )
    parser.add_argument(
        "--output", "-o",
        default="fer_plot.tex",
        help="Output .tex filename  (default: fer_plot.tex)",
    )
    parser.add_argument(
        "--labels", "-l",
        nargs="*",
        metavar="LABEL",
        help="Legend labels, one per directory.  Defaults to the directory name.",
    )
    parser.add_argument(
        "--xlabel",
        default=r"$\varepsilon$",
        help=r"x-axis label  (default: $\varepsilon$)",
    )
    parser.add_argument(
        "--ylabel",
        default=r"\ac{FER}",
        help=r"y-axis label  (default: \ac{FER})",
    )

    args = parser.parse_args()

    dirs = args.directories

    # Fill missing labels with directory names
    labels = list(args.labels) if args.labels else []
    while len(labels) < len(dirs):
        labels.append(make_label(dirs[len(labels)]))

    try:
        generate_tex(
            dirs=dirs,
            labels=labels,
            output=args.output,
            xlabel=args.xlabel,
            ylabel=args.ylabel,
        )
    except FileNotFoundError as e:
        print(f"[✗] Error: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()